### ISSUE TITLE
Error after update to v1.0.3

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.parser#12]
After updating the adpter to v1.0.3 the following messages appeared in the log and the instance restartet
`

parser.0 | 2018-08-09 17:47:11.765 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
-- | -- | -- | --
parser.0 | 2018-08-09 17:47:11.765 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:157:27)
parser.0 | 2018-08-09 17:47:11.765 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4332:61
parser.0 | 2018-08-09 17:47:11.765 | error | at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.parser/main.js:351:21)
parser.0 | 2018-08-09 17:47:11.765 | error | at poll (/opt/iobroker/node_modules/iobroker.parser/main.js:319:9)
parser.0 | 2018-08-09 17:47:11.765 | error | at readLink (/opt/iobroker/node_modules/iobroker.parser/main.js:294:13)
parser.0 | 2018-08-09 17:47:11.765 | error | at readLink (/opt/iobroker/node_modules/iobroker.parser/main.js:319:54)
parser.0 | 2018-08-09 17:47:11.765 | error | at analyseDataForStates (/opt/iobroker/node_modules/iobroker.parser/main.js:145:5)
parser.0 | 2018-08-09 17:47:11.765 | error | at _analyseDataForStates (/opt/iobroker/node_modules/iobroker.parser/main.js:127:9)
parser.0 | 2018-08-09 17:47:11.765 | error | at analyseData (/opt/iobroker/node_modules/iobroker.parser/main.js:195:29)
parser.0 | 2018-08-09 17:47:11.765 | error | TypeError: (data \|\| "").replace is not a function
parser.0 | 2018-08-09 17:47:11.763 | error | uncaught exception: (data \|\| "").replace is not a function
parser.0 | 2018-08-09 17:47:11.510 | info | starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.parser, node: v6.14.3

`

**Comment by GermanBluefox** [comment]
Fixed, please test

**Comment by GermanBluefox** [comment]
?
